version: '3.8'

services:
  postgres:
    container_name: forum-rp-db
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin123}
      POSTGRES_DB: ${DB_NAME:-forum_rp}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - forum-network

volumes:
  postgres_data:

networks:
  forum-network:
    driver: bridge
